/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuchungDankeRouteImport } from './routes/buchung/danke'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEinladungRouteImport } from './routes/admin/einladung'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedVerfuegbarkeitenRouteImport } from './routes/admin/_authenticated/verfuegbarkeiten'
import { Route as AdminAuthenticatedThemenRouteImport } from './routes/admin/_authenticated/themen'
import { Route as AdminAuthenticatedSchliesstageRouteImport } from './routes/admin/_authenticated/schliesstage'
import { Route as AdminAuthenticatedRaeumeRouteImport } from './routes/admin/_authenticated/raeume'
import { Route as AdminAuthenticatedMitarbeiterRouteImport } from './routes/admin/_authenticated/mitarbeiter'
import { Route as AdminAuthenticatedEinstellungenRouteImport } from './routes/admin/_authenticated/einstellungen'
import { Route as AdminAuthenticatedEinrichtungstypenRouteImport } from './routes/admin/_authenticated/einrichtungstypen'
import { Route as AdminAuthenticatedAuswertungenRouteImport } from './routes/admin/_authenticated/auswertungen'
import { Route as AdminAuthenticatedAngebotsartenRouteImport } from './routes/admin/_authenticated/angebotsarten'
import { Route as AdminAuthenticatedReferentenIndexRouteImport } from './routes/admin/_authenticated/referenten/index'
import { Route as AdminAuthenticatedBuchungenIndexRouteImport } from './routes/admin/_authenticated/buchungen/index'
import { Route as AdminAuthenticatedReferentenIdRouteImport } from './routes/admin/_authenticated/referenten/$id'
import { Route as AdminAuthenticatedBuchungenIdRouteImport } from './routes/admin/_authenticated/buchungen/$id'

const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchungDankeRoute = BuchungDankeRouteImport.update({
  id: '/buchung/danke',
  path: '/buchung/danke',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEinladungRoute = AdminEinladungRouteImport.update({
  id: '/admin/einladung',
  path: '/admin/einladung',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedVerfuegbarkeitenRoute =
  AdminAuthenticatedVerfuegbarkeitenRouteImport.update({
    id: '/verfuegbarkeiten',
    path: '/verfuegbarkeiten',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedThemenRoute =
  AdminAuthenticatedThemenRouteImport.update({
    id: '/themen',
    path: '/themen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedSchliesstageRoute =
  AdminAuthenticatedSchliesstageRouteImport.update({
    id: '/schliesstage',
    path: '/schliesstage',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedRaeumeRoute =
  AdminAuthenticatedRaeumeRouteImport.update({
    id: '/raeume',
    path: '/raeume',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMitarbeiterRoute =
  AdminAuthenticatedMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedEinstellungenRoute =
  AdminAuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedEinrichtungstypenRoute =
  AdminAuthenticatedEinrichtungstypenRouteImport.update({
    id: '/einrichtungstypen',
    path: '/einrichtungstypen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedAuswertungenRoute =
  AdminAuthenticatedAuswertungenRouteImport.update({
    id: '/auswertungen',
    path: '/auswertungen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedAngebotsartenRoute =
  AdminAuthenticatedAngebotsartenRouteImport.update({
    id: '/angebotsarten',
    path: '/angebotsarten',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedReferentenIndexRoute =
  AdminAuthenticatedReferentenIndexRouteImport.update({
    id: '/referenten/',
    path: '/referenten/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedBuchungenIndexRoute =
  AdminAuthenticatedBuchungenIndexRouteImport.update({
    id: '/buchungen/',
    path: '/buchungen/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedReferentenIdRoute =
  AdminAuthenticatedReferentenIdRouteImport.update({
    id: '/referenten/$id',
    path: '/referenten/$id',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedBuchungenIdRoute =
  AdminAuthenticatedBuchungenIdRouteImport.update({
    id: '/buchungen/$id',
    path: '/buchungen/$id',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/einladung': typeof AdminEinladungRoute
  '/admin/login': typeof AdminLoginRoute
  '/buchung/danke': typeof BuchungDankeRoute
  '/admin/angebotsarten': typeof AdminAuthenticatedAngebotsartenRoute
  '/admin/auswertungen': typeof AdminAuthenticatedAuswertungenRoute
  '/admin/einrichtungstypen': typeof AdminAuthenticatedEinrichtungstypenRoute
  '/admin/einstellungen': typeof AdminAuthenticatedEinstellungenRoute
  '/admin/mitarbeiter': typeof AdminAuthenticatedMitarbeiterRoute
  '/admin/raeume': typeof AdminAuthenticatedRaeumeRoute
  '/admin/schliesstage': typeof AdminAuthenticatedSchliesstageRoute
  '/admin/themen': typeof AdminAuthenticatedThemenRoute
  '/admin/verfuegbarkeiten': typeof AdminAuthenticatedVerfuegbarkeitenRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/buchungen/$id': typeof AdminAuthenticatedBuchungenIdRoute
  '/admin/referenten/$id': typeof AdminAuthenticatedReferentenIdRoute
  '/admin/buchungen/': typeof AdminAuthenticatedBuchungenIndexRoute
  '/admin/referenten/': typeof AdminAuthenticatedReferentenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/admin/einladung': typeof AdminEinladungRoute
  '/admin/login': typeof AdminLoginRoute
  '/buchung/danke': typeof BuchungDankeRoute
  '/admin/angebotsarten': typeof AdminAuthenticatedAngebotsartenRoute
  '/admin/auswertungen': typeof AdminAuthenticatedAuswertungenRoute
  '/admin/einrichtungstypen': typeof AdminAuthenticatedEinrichtungstypenRoute
  '/admin/einstellungen': typeof AdminAuthenticatedEinstellungenRoute
  '/admin/mitarbeiter': typeof AdminAuthenticatedMitarbeiterRoute
  '/admin/raeume': typeof AdminAuthenticatedRaeumeRoute
  '/admin/schliesstage': typeof AdminAuthenticatedSchliesstageRoute
  '/admin/themen': typeof AdminAuthenticatedThemenRoute
  '/admin/verfuegbarkeiten': typeof AdminAuthenticatedVerfuegbarkeitenRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admin/buchungen/$id': typeof AdminAuthenticatedBuchungenIdRoute
  '/admin/referenten/$id': typeof AdminAuthenticatedReferentenIdRoute
  '/admin/buchungen': typeof AdminAuthenticatedBuchungenIndexRoute
  '/admin/referenten': typeof AdminAuthenticatedReferentenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/einladung': typeof AdminEinladungRoute
  '/admin/login': typeof AdminLoginRoute
  '/buchung/danke': typeof BuchungDankeRoute
  '/admin/_authenticated/angebotsarten': typeof AdminAuthenticatedAngebotsartenRoute
  '/admin/_authenticated/auswertungen': typeof AdminAuthenticatedAuswertungenRoute
  '/admin/_authenticated/einrichtungstypen': typeof AdminAuthenticatedEinrichtungstypenRoute
  '/admin/_authenticated/einstellungen': typeof AdminAuthenticatedEinstellungenRoute
  '/admin/_authenticated/mitarbeiter': typeof AdminAuthenticatedMitarbeiterRoute
  '/admin/_authenticated/raeume': typeof AdminAuthenticatedRaeumeRoute
  '/admin/_authenticated/schliesstage': typeof AdminAuthenticatedSchliesstageRoute
  '/admin/_authenticated/themen': typeof AdminAuthenticatedThemenRoute
  '/admin/_authenticated/verfuegbarkeiten': typeof AdminAuthenticatedVerfuegbarkeitenRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/buchungen/$id': typeof AdminAuthenticatedBuchungenIdRoute
  '/admin/_authenticated/referenten/$id': typeof AdminAuthenticatedReferentenIdRoute
  '/admin/_authenticated/buchungen/': typeof AdminAuthenticatedBuchungenIndexRoute
  '/admin/_authenticated/referenten/': typeof AdminAuthenticatedReferentenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/admin'
    | '/admin/einladung'
    | '/admin/login'
    | '/buchung/danke'
    | '/admin/angebotsarten'
    | '/admin/auswertungen'
    | '/admin/einrichtungstypen'
    | '/admin/einstellungen'
    | '/admin/mitarbeiter'
    | '/admin/raeume'
    | '/admin/schliesstage'
    | '/admin/themen'
    | '/admin/verfuegbarkeiten'
    | '/admin/'
    | '/admin/buchungen/$id'
    | '/admin/referenten/$id'
    | '/admin/buchungen/'
    | '/admin/referenten/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/admin/einladung'
    | '/admin/login'
    | '/buchung/danke'
    | '/admin/angebotsarten'
    | '/admin/auswertungen'
    | '/admin/einrichtungstypen'
    | '/admin/einstellungen'
    | '/admin/mitarbeiter'
    | '/admin/raeume'
    | '/admin/schliesstage'
    | '/admin/themen'
    | '/admin/verfuegbarkeiten'
    | '/admin'
    | '/admin/buchungen/$id'
    | '/admin/referenten/$id'
    | '/admin/buchungen'
    | '/admin/referenten'
  id:
    | '__root__'
    | '/'
    | '/embed'
    | '/admin/_authenticated'
    | '/admin/einladung'
    | '/admin/login'
    | '/buchung/danke'
    | '/admin/_authenticated/angebotsarten'
    | '/admin/_authenticated/auswertungen'
    | '/admin/_authenticated/einrichtungstypen'
    | '/admin/_authenticated/einstellungen'
    | '/admin/_authenticated/mitarbeiter'
    | '/admin/_authenticated/raeume'
    | '/admin/_authenticated/schliesstage'
    | '/admin/_authenticated/themen'
    | '/admin/_authenticated/verfuegbarkeiten'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/buchungen/$id'
    | '/admin/_authenticated/referenten/$id'
    | '/admin/_authenticated/buchungen/'
    | '/admin/_authenticated/referenten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminEinladungRoute: typeof AdminEinladungRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BuchungDankeRoute: typeof BuchungDankeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchung/danke': {
      id: '/buchung/danke'
      path: '/buchung/danke'
      fullPath: '/buchung/danke'
      preLoaderRoute: typeof BuchungDankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/einladung': {
      id: '/admin/einladung'
      path: '/admin/einladung'
      fullPath: '/admin/einladung'
      preLoaderRoute: typeof AdminEinladungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/verfuegbarkeiten': {
      id: '/admin/_authenticated/verfuegbarkeiten'
      path: '/verfuegbarkeiten'
      fullPath: '/admin/verfuegbarkeiten'
      preLoaderRoute: typeof AdminAuthenticatedVerfuegbarkeitenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/themen': {
      id: '/admin/_authenticated/themen'
      path: '/themen'
      fullPath: '/admin/themen'
      preLoaderRoute: typeof AdminAuthenticatedThemenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/schliesstage': {
      id: '/admin/_authenticated/schliesstage'
      path: '/schliesstage'
      fullPath: '/admin/schliesstage'
      preLoaderRoute: typeof AdminAuthenticatedSchliesstageRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/raeume': {
      id: '/admin/_authenticated/raeume'
      path: '/raeume'
      fullPath: '/admin/raeume'
      preLoaderRoute: typeof AdminAuthenticatedRaeumeRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/mitarbeiter': {
      id: '/admin/_authenticated/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/admin/mitarbeiter'
      preLoaderRoute: typeof AdminAuthenticatedMitarbeiterRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/einstellungen': {
      id: '/admin/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AdminAuthenticatedEinstellungenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/einrichtungstypen': {
      id: '/admin/_authenticated/einrichtungstypen'
      path: '/einrichtungstypen'
      fullPath: '/admin/einrichtungstypen'
      preLoaderRoute: typeof AdminAuthenticatedEinrichtungstypenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/auswertungen': {
      id: '/admin/_authenticated/auswertungen'
      path: '/auswertungen'
      fullPath: '/admin/auswertungen'
      preLoaderRoute: typeof AdminAuthenticatedAuswertungenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/angebotsarten': {
      id: '/admin/_authenticated/angebotsarten'
      path: '/angebotsarten'
      fullPath: '/admin/angebotsarten'
      preLoaderRoute: typeof AdminAuthenticatedAngebotsartenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/referenten/': {
      id: '/admin/_authenticated/referenten/'
      path: '/referenten'
      fullPath: '/admin/referenten/'
      preLoaderRoute: typeof AdminAuthenticatedReferentenIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/buchungen/': {
      id: '/admin/_authenticated/buchungen/'
      path: '/buchungen'
      fullPath: '/admin/buchungen/'
      preLoaderRoute: typeof AdminAuthenticatedBuchungenIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/referenten/$id': {
      id: '/admin/_authenticated/referenten/$id'
      path: '/referenten/$id'
      fullPath: '/admin/referenten/$id'
      preLoaderRoute: typeof AdminAuthenticatedReferentenIdRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/buchungen/$id': {
      id: '/admin/_authenticated/buchungen/$id'
      path: '/buchungen/$id'
      fullPath: '/admin/buchungen/$id'
      preLoaderRoute: typeof AdminAuthenticatedBuchungenIdRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedAngebotsartenRoute: typeof AdminAuthenticatedAngebotsartenRoute
  AdminAuthenticatedAuswertungenRoute: typeof AdminAuthenticatedAuswertungenRoute
  AdminAuthenticatedEinrichtungstypenRoute: typeof AdminAuthenticatedEinrichtungstypenRoute
  AdminAuthenticatedEinstellungenRoute: typeof AdminAuthenticatedEinstellungenRoute
  AdminAuthenticatedMitarbeiterRoute: typeof AdminAuthenticatedMitarbeiterRoute
  AdminAuthenticatedRaeumeRoute: typeof AdminAuthenticatedRaeumeRoute
  AdminAuthenticatedSchliesstageRoute: typeof AdminAuthenticatedSchliesstageRoute
  AdminAuthenticatedThemenRoute: typeof AdminAuthenticatedThemenRoute
  AdminAuthenticatedVerfuegbarkeitenRoute: typeof AdminAuthenticatedVerfuegbarkeitenRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
  AdminAuthenticatedBuchungenIdRoute: typeof AdminAuthenticatedBuchungenIdRoute
  AdminAuthenticatedReferentenIdRoute: typeof AdminAuthenticatedReferentenIdRoute
  AdminAuthenticatedBuchungenIndexRoute: typeof AdminAuthenticatedBuchungenIndexRoute
  AdminAuthenticatedReferentenIndexRoute: typeof AdminAuthenticatedReferentenIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedAngebotsartenRoute: AdminAuthenticatedAngebotsartenRoute,
  AdminAuthenticatedAuswertungenRoute: AdminAuthenticatedAuswertungenRoute,
  AdminAuthenticatedEinrichtungstypenRoute:
    AdminAuthenticatedEinrichtungstypenRoute,
  AdminAuthenticatedEinstellungenRoute: AdminAuthenticatedEinstellungenRoute,
  AdminAuthenticatedMitarbeiterRoute: AdminAuthenticatedMitarbeiterRoute,
  AdminAuthenticatedRaeumeRoute: AdminAuthenticatedRaeumeRoute,
  AdminAuthenticatedSchliesstageRoute: AdminAuthenticatedSchliesstageRoute,
  AdminAuthenticatedThemenRoute: AdminAuthenticatedThemenRoute,
  AdminAuthenticatedVerfuegbarkeitenRoute:
    AdminAuthenticatedVerfuegbarkeitenRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
  AdminAuthenticatedBuchungenIdRoute: AdminAuthenticatedBuchungenIdRoute,
  AdminAuthenticatedReferentenIdRoute: AdminAuthenticatedReferentenIdRoute,
  AdminAuthenticatedBuchungenIndexRoute: AdminAuthenticatedBuchungenIndexRoute,
  AdminAuthenticatedReferentenIndexRoute:
    AdminAuthenticatedReferentenIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminEinladungRoute: AdminEinladungRoute,
  AdminLoginRoute: AdminLoginRoute,
  BuchungDankeRoute: BuchungDankeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
