/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuchungDankeRouteImport } from './routes/buchung/danke'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEinladungRouteImport } from './routes/admin/einladung'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedVerwaltungRouteImport } from './routes/admin/_authenticated/verwaltung'
import { Route as AdminAuthenticatedThemenRouteImport } from './routes/admin/_authenticated/themen'
import { Route as AdminAuthenticatedTestRouteImport } from './routes/admin/_authenticated/test'
import { Route as AdminAuthenticatedStammdatenRouteImport } from './routes/admin/_authenticated/stammdaten'
import { Route as AdminAuthenticatedSchliesstageRouteImport } from './routes/admin/_authenticated/schliesstage'
import { Route as AdminAuthenticatedRaeumeRouteImport } from './routes/admin/_authenticated/raeume'
import { Route as AdminAuthenticatedMitarbeiterRouteImport } from './routes/admin/_authenticated/mitarbeiter'
import { Route as AdminAuthenticatedMarktueberblickRouteImport } from './routes/admin/_authenticated/marktueberblick'
import { Route as AdminAuthenticatedKalenderRouteImport } from './routes/admin/_authenticated/kalender'
import { Route as AdminAuthenticatedEinstellungenRouteImport } from './routes/admin/_authenticated/einstellungen'
import { Route as AdminAuthenticatedEinrichtungstypenRouteImport } from './routes/admin/_authenticated/einrichtungstypen'
import { Route as AdminAuthenticatedEinbettenRouteImport } from './routes/admin/_authenticated/einbetten'
import { Route as AdminAuthenticatedAuswertungenRouteImport } from './routes/admin/_authenticated/auswertungen'
import { Route as AdminAuthenticatedAngebotsartenRouteImport } from './routes/admin/_authenticated/angebotsarten'
import { Route as AdminAuthenticatedVerwaltungIndexRouteImport } from './routes/admin/_authenticated/verwaltung/index'
import { Route as AdminAuthenticatedStammdatenIndexRouteImport } from './routes/admin/_authenticated/stammdaten/index'
import { Route as AdminAuthenticatedReferentenIndexRouteImport } from './routes/admin/_authenticated/referenten/index'
import { Route as AdminAuthenticatedHilfeIndexRouteImport } from './routes/admin/_authenticated/hilfe/index'
import { Route as AdminAuthenticatedBuchungenIndexRouteImport } from './routes/admin/_authenticated/buchungen/index'
import { Route as AdminAuthenticatedVerwaltungMitarbeiterRouteImport } from './routes/admin/_authenticated/verwaltung/mitarbeiter'
import { Route as AdminAuthenticatedVerwaltungEinstellungenRouteImport } from './routes/admin/_authenticated/verwaltung/einstellungen'
import { Route as AdminAuthenticatedVerwaltungEinbettenRouteImport } from './routes/admin/_authenticated/verwaltung/einbetten'
import { Route as AdminAuthenticatedStammdatenThemenRouteImport } from './routes/admin/_authenticated/stammdaten/themen'
import { Route as AdminAuthenticatedStammdatenSchliesstageRouteImport } from './routes/admin/_authenticated/stammdaten/schliesstage'
import { Route as AdminAuthenticatedStammdatenRaeumeRouteImport } from './routes/admin/_authenticated/stammdaten/raeume'
import { Route as AdminAuthenticatedStammdatenEinrichtungstypenRouteImport } from './routes/admin/_authenticated/stammdaten/einrichtungstypen'
import { Route as AdminAuthenticatedStammdatenAngebotsartenRouteImport } from './routes/admin/_authenticated/stammdaten/angebotsarten'
import { Route as AdminAuthenticatedReferentenIdRouteImport } from './routes/admin/_authenticated/referenten/$id'
import { Route as AdminAuthenticatedHilfeMarktueberblickRouteImport } from './routes/admin/_authenticated/hilfe/marktueberblick'
import { Route as AdminAuthenticatedBuchungenNeuRouteImport } from './routes/admin/_authenticated/buchungen/neu'
import { Route as AdminAuthenticatedBuchungenIdRouteImport } from './routes/admin/_authenticated/buchungen/$id'

const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchungDankeRoute = BuchungDankeRouteImport.update({
  id: '/buchung/danke',
  path: '/buchung/danke',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEinladungRoute = AdminEinladungRouteImport.update({
  id: '/admin/einladung',
  path: '/admin/einladung',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedVerwaltungRoute =
  AdminAuthenticatedVerwaltungRouteImport.update({
    id: '/verwaltung',
    path: '/verwaltung',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedThemenRoute =
  AdminAuthenticatedThemenRouteImport.update({
    id: '/themen',
    path: '/themen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedTestRoute = AdminAuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedStammdatenRoute =
  AdminAuthenticatedStammdatenRouteImport.update({
    id: '/stammdaten',
    path: '/stammdaten',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedSchliesstageRoute =
  AdminAuthenticatedSchliesstageRouteImport.update({
    id: '/schliesstage',
    path: '/schliesstage',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedRaeumeRoute =
  AdminAuthenticatedRaeumeRouteImport.update({
    id: '/raeume',
    path: '/raeume',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMitarbeiterRoute =
  AdminAuthenticatedMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedMarktueberblickRoute =
  AdminAuthenticatedMarktueberblickRouteImport.update({
    id: '/marktueberblick',
    path: '/marktueberblick',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedKalenderRoute =
  AdminAuthenticatedKalenderRouteImport.update({
    id: '/kalender',
    path: '/kalender',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedEinstellungenRoute =
  AdminAuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedEinrichtungstypenRoute =
  AdminAuthenticatedEinrichtungstypenRouteImport.update({
    id: '/einrichtungstypen',
    path: '/einrichtungstypen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedEinbettenRoute =
  AdminAuthenticatedEinbettenRouteImport.update({
    id: '/einbetten',
    path: '/einbetten',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedAuswertungenRoute =
  AdminAuthenticatedAuswertungenRouteImport.update({
    id: '/auswertungen',
    path: '/auswertungen',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedAngebotsartenRoute =
  AdminAuthenticatedAngebotsartenRouteImport.update({
    id: '/angebotsarten',
    path: '/angebotsarten',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedVerwaltungIndexRoute =
  AdminAuthenticatedVerwaltungIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedVerwaltungRoute,
  } as any)
const AdminAuthenticatedStammdatenIndexRoute =
  AdminAuthenticatedStammdatenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedStammdatenRoute,
  } as any)
const AdminAuthenticatedReferentenIndexRoute =
  AdminAuthenticatedReferentenIndexRouteImport.update({
    id: '/referenten/',
    path: '/referenten/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedHilfeIndexRoute =
  AdminAuthenticatedHilfeIndexRouteImport.update({
    id: '/hilfe/',
    path: '/hilfe/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedBuchungenIndexRoute =
  AdminAuthenticatedBuchungenIndexRouteImport.update({
    id: '/buchungen/',
    path: '/buchungen/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedVerwaltungMitarbeiterRoute =
  AdminAuthenticatedVerwaltungMitarbeiterRouteImport.update({
    id: '/mitarbeiter',
    path: '/mitarbeiter',
    getParentRoute: () => AdminAuthenticatedVerwaltungRoute,
  } as any)
const AdminAuthenticatedVerwaltungEinstellungenRoute =
  AdminAuthenticatedVerwaltungEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AdminAuthenticatedVerwaltungRoute,
  } as any)
const AdminAuthenticatedVerwaltungEinbettenRoute =
  AdminAuthenticatedVerwaltungEinbettenRouteImport.update({
    id: '/einbetten',
    path: '/einbetten',
    getParentRoute: () => AdminAuthenticatedVerwaltungRoute,
  } as any)
const AdminAuthenticatedStammdatenThemenRoute =
  AdminAuthenticatedStammdatenThemenRouteImport.update({
    id: '/themen',
    path: '/themen',
    getParentRoute: () => AdminAuthenticatedStammdatenRoute,
  } as any)
const AdminAuthenticatedStammdatenSchliesstageRoute =
  AdminAuthenticatedStammdatenSchliesstageRouteImport.update({
    id: '/schliesstage',
    path: '/schliesstage',
    getParentRoute: () => AdminAuthenticatedStammdatenRoute,
  } as any)
const AdminAuthenticatedStammdatenRaeumeRoute =
  AdminAuthenticatedStammdatenRaeumeRouteImport.update({
    id: '/raeume',
    path: '/raeume',
    getParentRoute: () => AdminAuthenticatedStammdatenRoute,
  } as any)
const AdminAuthenticatedStammdatenEinrichtungstypenRoute =
  AdminAuthenticatedStammdatenEinrichtungstypenRouteImport.update({
    id: '/einrichtungstypen',
    path: '/einrichtungstypen',
    getParentRoute: () => AdminAuthenticatedStammdatenRoute,
  } as any)
const AdminAuthenticatedStammdatenAngebotsartenRoute =
  AdminAuthenticatedStammdatenAngebotsartenRouteImport.update({
    id: '/angebotsarten',
    path: '/angebotsarten',
    getParentRoute: () => AdminAuthenticatedStammdatenRoute,
  } as any)
const AdminAuthenticatedReferentenIdRoute =
  AdminAuthenticatedReferentenIdRouteImport.update({
    id: '/referenten/$id',
    path: '/referenten/$id',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedHilfeMarktueberblickRoute =
  AdminAuthenticatedHilfeMarktueberblickRouteImport.update({
    id: '/hilfe/marktueberblick',
    path: '/hilfe/marktueberblick',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedBuchungenNeuRoute =
  AdminAuthenticatedBuchungenNeuRouteImport.update({
    id: '/buchungen/neu',
    path: '/buchungen/neu',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedBuchungenIdRoute =
  AdminAuthenticatedBuchungenIdRouteImport.update({
    id: '/buchungen/$id',
    path: '/buchungen/$id',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/admin/einladung': typeof AdminEinladungRoute
  '/admin/login': typeof AdminLoginRoute
  '/buchung/danke': typeof BuchungDankeRoute
  '/admin/angebotsarten': typeof AdminAuthenticatedAngebotsartenRoute
  '/admin/auswertungen': typeof AdminAuthenticatedAuswertungenRoute
  '/admin/einbetten': typeof AdminAuthenticatedEinbettenRoute
  '/admin/einrichtungstypen': typeof AdminAuthenticatedEinrichtungstypenRoute
  '/admin/einstellungen': typeof AdminAuthenticatedEinstellungenRoute
  '/admin/kalender': typeof AdminAuthenticatedKalenderRoute
  '/admin/marktueberblick': typeof AdminAuthenticatedMarktueberblickRoute
  '/admin/mitarbeiter': typeof AdminAuthenticatedMitarbeiterRoute
  '/admin/raeume': typeof AdminAuthenticatedRaeumeRoute
  '/admin/schliesstage': typeof AdminAuthenticatedSchliesstageRoute
  '/admin/stammdaten': typeof AdminAuthenticatedStammdatenRouteWithChildren
  '/admin/test': typeof AdminAuthenticatedTestRoute
  '/admin/themen': typeof AdminAuthenticatedThemenRoute
  '/admin/verwaltung': typeof AdminAuthenticatedVerwaltungRouteWithChildren
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/buchungen/$id': typeof AdminAuthenticatedBuchungenIdRoute
  '/admin/buchungen/neu': typeof AdminAuthenticatedBuchungenNeuRoute
  '/admin/hilfe/marktueberblick': typeof AdminAuthenticatedHilfeMarktueberblickRoute
  '/admin/referenten/$id': typeof AdminAuthenticatedReferentenIdRoute
  '/admin/stammdaten/angebotsarten': typeof AdminAuthenticatedStammdatenAngebotsartenRoute
  '/admin/stammdaten/einrichtungstypen': typeof AdminAuthenticatedStammdatenEinrichtungstypenRoute
  '/admin/stammdaten/raeume': typeof AdminAuthenticatedStammdatenRaeumeRoute
  '/admin/stammdaten/schliesstage': typeof AdminAuthenticatedStammdatenSchliesstageRoute
  '/admin/stammdaten/themen': typeof AdminAuthenticatedStammdatenThemenRoute
  '/admin/verwaltung/einbetten': typeof AdminAuthenticatedVerwaltungEinbettenRoute
  '/admin/verwaltung/einstellungen': typeof AdminAuthenticatedVerwaltungEinstellungenRoute
  '/admin/verwaltung/mitarbeiter': typeof AdminAuthenticatedVerwaltungMitarbeiterRoute
  '/admin/buchungen/': typeof AdminAuthenticatedBuchungenIndexRoute
  '/admin/hilfe/': typeof AdminAuthenticatedHilfeIndexRoute
  '/admin/referenten/': typeof AdminAuthenticatedReferentenIndexRoute
  '/admin/stammdaten/': typeof AdminAuthenticatedStammdatenIndexRoute
  '/admin/verwaltung/': typeof AdminAuthenticatedVerwaltungIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/admin/einladung': typeof AdminEinladungRoute
  '/admin/login': typeof AdminLoginRoute
  '/buchung/danke': typeof BuchungDankeRoute
  '/admin/angebotsarten': typeof AdminAuthenticatedAngebotsartenRoute
  '/admin/auswertungen': typeof AdminAuthenticatedAuswertungenRoute
  '/admin/einbetten': typeof AdminAuthenticatedEinbettenRoute
  '/admin/einrichtungstypen': typeof AdminAuthenticatedEinrichtungstypenRoute
  '/admin/einstellungen': typeof AdminAuthenticatedEinstellungenRoute
  '/admin/kalender': typeof AdminAuthenticatedKalenderRoute
  '/admin/marktueberblick': typeof AdminAuthenticatedMarktueberblickRoute
  '/admin/mitarbeiter': typeof AdminAuthenticatedMitarbeiterRoute
  '/admin/raeume': typeof AdminAuthenticatedRaeumeRoute
  '/admin/schliesstage': typeof AdminAuthenticatedSchliesstageRoute
  '/admin/test': typeof AdminAuthenticatedTestRoute
  '/admin/themen': typeof AdminAuthenticatedThemenRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admin/buchungen/$id': typeof AdminAuthenticatedBuchungenIdRoute
  '/admin/buchungen/neu': typeof AdminAuthenticatedBuchungenNeuRoute
  '/admin/hilfe/marktueberblick': typeof AdminAuthenticatedHilfeMarktueberblickRoute
  '/admin/referenten/$id': typeof AdminAuthenticatedReferentenIdRoute
  '/admin/stammdaten/angebotsarten': typeof AdminAuthenticatedStammdatenAngebotsartenRoute
  '/admin/stammdaten/einrichtungstypen': typeof AdminAuthenticatedStammdatenEinrichtungstypenRoute
  '/admin/stammdaten/raeume': typeof AdminAuthenticatedStammdatenRaeumeRoute
  '/admin/stammdaten/schliesstage': typeof AdminAuthenticatedStammdatenSchliesstageRoute
  '/admin/stammdaten/themen': typeof AdminAuthenticatedStammdatenThemenRoute
  '/admin/verwaltung/einbetten': typeof AdminAuthenticatedVerwaltungEinbettenRoute
  '/admin/verwaltung/einstellungen': typeof AdminAuthenticatedVerwaltungEinstellungenRoute
  '/admin/verwaltung/mitarbeiter': typeof AdminAuthenticatedVerwaltungMitarbeiterRoute
  '/admin/buchungen': typeof AdminAuthenticatedBuchungenIndexRoute
  '/admin/hilfe': typeof AdminAuthenticatedHilfeIndexRoute
  '/admin/referenten': typeof AdminAuthenticatedReferentenIndexRoute
  '/admin/stammdaten': typeof AdminAuthenticatedStammdatenIndexRoute
  '/admin/verwaltung': typeof AdminAuthenticatedVerwaltungIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/einladung': typeof AdminEinladungRoute
  '/admin/login': typeof AdminLoginRoute
  '/buchung/danke': typeof BuchungDankeRoute
  '/admin/_authenticated/angebotsarten': typeof AdminAuthenticatedAngebotsartenRoute
  '/admin/_authenticated/auswertungen': typeof AdminAuthenticatedAuswertungenRoute
  '/admin/_authenticated/einbetten': typeof AdminAuthenticatedEinbettenRoute
  '/admin/_authenticated/einrichtungstypen': typeof AdminAuthenticatedEinrichtungstypenRoute
  '/admin/_authenticated/einstellungen': typeof AdminAuthenticatedEinstellungenRoute
  '/admin/_authenticated/kalender': typeof AdminAuthenticatedKalenderRoute
  '/admin/_authenticated/marktueberblick': typeof AdminAuthenticatedMarktueberblickRoute
  '/admin/_authenticated/mitarbeiter': typeof AdminAuthenticatedMitarbeiterRoute
  '/admin/_authenticated/raeume': typeof AdminAuthenticatedRaeumeRoute
  '/admin/_authenticated/schliesstage': typeof AdminAuthenticatedSchliesstageRoute
  '/admin/_authenticated/stammdaten': typeof AdminAuthenticatedStammdatenRouteWithChildren
  '/admin/_authenticated/test': typeof AdminAuthenticatedTestRoute
  '/admin/_authenticated/themen': typeof AdminAuthenticatedThemenRoute
  '/admin/_authenticated/verwaltung': typeof AdminAuthenticatedVerwaltungRouteWithChildren
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/buchungen/$id': typeof AdminAuthenticatedBuchungenIdRoute
  '/admin/_authenticated/buchungen/neu': typeof AdminAuthenticatedBuchungenNeuRoute
  '/admin/_authenticated/hilfe/marktueberblick': typeof AdminAuthenticatedHilfeMarktueberblickRoute
  '/admin/_authenticated/referenten/$id': typeof AdminAuthenticatedReferentenIdRoute
  '/admin/_authenticated/stammdaten/angebotsarten': typeof AdminAuthenticatedStammdatenAngebotsartenRoute
  '/admin/_authenticated/stammdaten/einrichtungstypen': typeof AdminAuthenticatedStammdatenEinrichtungstypenRoute
  '/admin/_authenticated/stammdaten/raeume': typeof AdminAuthenticatedStammdatenRaeumeRoute
  '/admin/_authenticated/stammdaten/schliesstage': typeof AdminAuthenticatedStammdatenSchliesstageRoute
  '/admin/_authenticated/stammdaten/themen': typeof AdminAuthenticatedStammdatenThemenRoute
  '/admin/_authenticated/verwaltung/einbetten': typeof AdminAuthenticatedVerwaltungEinbettenRoute
  '/admin/_authenticated/verwaltung/einstellungen': typeof AdminAuthenticatedVerwaltungEinstellungenRoute
  '/admin/_authenticated/verwaltung/mitarbeiter': typeof AdminAuthenticatedVerwaltungMitarbeiterRoute
  '/admin/_authenticated/buchungen/': typeof AdminAuthenticatedBuchungenIndexRoute
  '/admin/_authenticated/hilfe/': typeof AdminAuthenticatedHilfeIndexRoute
  '/admin/_authenticated/referenten/': typeof AdminAuthenticatedReferentenIndexRoute
  '/admin/_authenticated/stammdaten/': typeof AdminAuthenticatedStammdatenIndexRoute
  '/admin/_authenticated/verwaltung/': typeof AdminAuthenticatedVerwaltungIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/admin'
    | '/admin/einladung'
    | '/admin/login'
    | '/buchung/danke'
    | '/admin/angebotsarten'
    | '/admin/auswertungen'
    | '/admin/einbetten'
    | '/admin/einrichtungstypen'
    | '/admin/einstellungen'
    | '/admin/kalender'
    | '/admin/marktueberblick'
    | '/admin/mitarbeiter'
    | '/admin/raeume'
    | '/admin/schliesstage'
    | '/admin/stammdaten'
    | '/admin/test'
    | '/admin/themen'
    | '/admin/verwaltung'
    | '/admin/'
    | '/admin/buchungen/$id'
    | '/admin/buchungen/neu'
    | '/admin/hilfe/marktueberblick'
    | '/admin/referenten/$id'
    | '/admin/stammdaten/angebotsarten'
    | '/admin/stammdaten/einrichtungstypen'
    | '/admin/stammdaten/raeume'
    | '/admin/stammdaten/schliesstage'
    | '/admin/stammdaten/themen'
    | '/admin/verwaltung/einbetten'
    | '/admin/verwaltung/einstellungen'
    | '/admin/verwaltung/mitarbeiter'
    | '/admin/buchungen/'
    | '/admin/hilfe/'
    | '/admin/referenten/'
    | '/admin/stammdaten/'
    | '/admin/verwaltung/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/admin/einladung'
    | '/admin/login'
    | '/buchung/danke'
    | '/admin/angebotsarten'
    | '/admin/auswertungen'
    | '/admin/einbetten'
    | '/admin/einrichtungstypen'
    | '/admin/einstellungen'
    | '/admin/kalender'
    | '/admin/marktueberblick'
    | '/admin/mitarbeiter'
    | '/admin/raeume'
    | '/admin/schliesstage'
    | '/admin/test'
    | '/admin/themen'
    | '/admin'
    | '/admin/buchungen/$id'
    | '/admin/buchungen/neu'
    | '/admin/hilfe/marktueberblick'
    | '/admin/referenten/$id'
    | '/admin/stammdaten/angebotsarten'
    | '/admin/stammdaten/einrichtungstypen'
    | '/admin/stammdaten/raeume'
    | '/admin/stammdaten/schliesstage'
    | '/admin/stammdaten/themen'
    | '/admin/verwaltung/einbetten'
    | '/admin/verwaltung/einstellungen'
    | '/admin/verwaltung/mitarbeiter'
    | '/admin/buchungen'
    | '/admin/hilfe'
    | '/admin/referenten'
    | '/admin/stammdaten'
    | '/admin/verwaltung'
  id:
    | '__root__'
    | '/'
    | '/embed'
    | '/admin/_authenticated'
    | '/admin/einladung'
    | '/admin/login'
    | '/buchung/danke'
    | '/admin/_authenticated/angebotsarten'
    | '/admin/_authenticated/auswertungen'
    | '/admin/_authenticated/einbetten'
    | '/admin/_authenticated/einrichtungstypen'
    | '/admin/_authenticated/einstellungen'
    | '/admin/_authenticated/kalender'
    | '/admin/_authenticated/marktueberblick'
    | '/admin/_authenticated/mitarbeiter'
    | '/admin/_authenticated/raeume'
    | '/admin/_authenticated/schliesstage'
    | '/admin/_authenticated/stammdaten'
    | '/admin/_authenticated/test'
    | '/admin/_authenticated/themen'
    | '/admin/_authenticated/verwaltung'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/buchungen/$id'
    | '/admin/_authenticated/buchungen/neu'
    | '/admin/_authenticated/hilfe/marktueberblick'
    | '/admin/_authenticated/referenten/$id'
    | '/admin/_authenticated/stammdaten/angebotsarten'
    | '/admin/_authenticated/stammdaten/einrichtungstypen'
    | '/admin/_authenticated/stammdaten/raeume'
    | '/admin/_authenticated/stammdaten/schliesstage'
    | '/admin/_authenticated/stammdaten/themen'
    | '/admin/_authenticated/verwaltung/einbetten'
    | '/admin/_authenticated/verwaltung/einstellungen'
    | '/admin/_authenticated/verwaltung/mitarbeiter'
    | '/admin/_authenticated/buchungen/'
    | '/admin/_authenticated/hilfe/'
    | '/admin/_authenticated/referenten/'
    | '/admin/_authenticated/stammdaten/'
    | '/admin/_authenticated/verwaltung/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminEinladungRoute: typeof AdminEinladungRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BuchungDankeRoute: typeof BuchungDankeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchung/danke': {
      id: '/buchung/danke'
      path: '/buchung/danke'
      fullPath: '/buchung/danke'
      preLoaderRoute: typeof BuchungDankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/einladung': {
      id: '/admin/einladung'
      path: '/admin/einladung'
      fullPath: '/admin/einladung'
      preLoaderRoute: typeof AdminEinladungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/verwaltung': {
      id: '/admin/_authenticated/verwaltung'
      path: '/verwaltung'
      fullPath: '/admin/verwaltung'
      preLoaderRoute: typeof AdminAuthenticatedVerwaltungRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/themen': {
      id: '/admin/_authenticated/themen'
      path: '/themen'
      fullPath: '/admin/themen'
      preLoaderRoute: typeof AdminAuthenticatedThemenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/test': {
      id: '/admin/_authenticated/test'
      path: '/test'
      fullPath: '/admin/test'
      preLoaderRoute: typeof AdminAuthenticatedTestRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/stammdaten': {
      id: '/admin/_authenticated/stammdaten'
      path: '/stammdaten'
      fullPath: '/admin/stammdaten'
      preLoaderRoute: typeof AdminAuthenticatedStammdatenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/schliesstage': {
      id: '/admin/_authenticated/schliesstage'
      path: '/schliesstage'
      fullPath: '/admin/schliesstage'
      preLoaderRoute: typeof AdminAuthenticatedSchliesstageRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/raeume': {
      id: '/admin/_authenticated/raeume'
      path: '/raeume'
      fullPath: '/admin/raeume'
      preLoaderRoute: typeof AdminAuthenticatedRaeumeRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/mitarbeiter': {
      id: '/admin/_authenticated/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/admin/mitarbeiter'
      preLoaderRoute: typeof AdminAuthenticatedMitarbeiterRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/marktueberblick': {
      id: '/admin/_authenticated/marktueberblick'
      path: '/marktueberblick'
      fullPath: '/admin/marktueberblick'
      preLoaderRoute: typeof AdminAuthenticatedMarktueberblickRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/kalender': {
      id: '/admin/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/admin/kalender'
      preLoaderRoute: typeof AdminAuthenticatedKalenderRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/einstellungen': {
      id: '/admin/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AdminAuthenticatedEinstellungenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/einrichtungstypen': {
      id: '/admin/_authenticated/einrichtungstypen'
      path: '/einrichtungstypen'
      fullPath: '/admin/einrichtungstypen'
      preLoaderRoute: typeof AdminAuthenticatedEinrichtungstypenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/einbetten': {
      id: '/admin/_authenticated/einbetten'
      path: '/einbetten'
      fullPath: '/admin/einbetten'
      preLoaderRoute: typeof AdminAuthenticatedEinbettenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/auswertungen': {
      id: '/admin/_authenticated/auswertungen'
      path: '/auswertungen'
      fullPath: '/admin/auswertungen'
      preLoaderRoute: typeof AdminAuthenticatedAuswertungenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/angebotsarten': {
      id: '/admin/_authenticated/angebotsarten'
      path: '/angebotsarten'
      fullPath: '/admin/angebotsarten'
      preLoaderRoute: typeof AdminAuthenticatedAngebotsartenRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/verwaltung/': {
      id: '/admin/_authenticated/verwaltung/'
      path: '/'
      fullPath: '/admin/verwaltung/'
      preLoaderRoute: typeof AdminAuthenticatedVerwaltungIndexRouteImport
      parentRoute: typeof AdminAuthenticatedVerwaltungRoute
    }
    '/admin/_authenticated/stammdaten/': {
      id: '/admin/_authenticated/stammdaten/'
      path: '/'
      fullPath: '/admin/stammdaten/'
      preLoaderRoute: typeof AdminAuthenticatedStammdatenIndexRouteImport
      parentRoute: typeof AdminAuthenticatedStammdatenRoute
    }
    '/admin/_authenticated/referenten/': {
      id: '/admin/_authenticated/referenten/'
      path: '/referenten'
      fullPath: '/admin/referenten/'
      preLoaderRoute: typeof AdminAuthenticatedReferentenIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/hilfe/': {
      id: '/admin/_authenticated/hilfe/'
      path: '/hilfe'
      fullPath: '/admin/hilfe/'
      preLoaderRoute: typeof AdminAuthenticatedHilfeIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/buchungen/': {
      id: '/admin/_authenticated/buchungen/'
      path: '/buchungen'
      fullPath: '/admin/buchungen/'
      preLoaderRoute: typeof AdminAuthenticatedBuchungenIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/verwaltung/mitarbeiter': {
      id: '/admin/_authenticated/verwaltung/mitarbeiter'
      path: '/mitarbeiter'
      fullPath: '/admin/verwaltung/mitarbeiter'
      preLoaderRoute: typeof AdminAuthenticatedVerwaltungMitarbeiterRouteImport
      parentRoute: typeof AdminAuthenticatedVerwaltungRoute
    }
    '/admin/_authenticated/verwaltung/einstellungen': {
      id: '/admin/_authenticated/verwaltung/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/verwaltung/einstellungen'
      preLoaderRoute: typeof AdminAuthenticatedVerwaltungEinstellungenRouteImport
      parentRoute: typeof AdminAuthenticatedVerwaltungRoute
    }
    '/admin/_authenticated/verwaltung/einbetten': {
      id: '/admin/_authenticated/verwaltung/einbetten'
      path: '/einbetten'
      fullPath: '/admin/verwaltung/einbetten'
      preLoaderRoute: typeof AdminAuthenticatedVerwaltungEinbettenRouteImport
      parentRoute: typeof AdminAuthenticatedVerwaltungRoute
    }
    '/admin/_authenticated/stammdaten/themen': {
      id: '/admin/_authenticated/stammdaten/themen'
      path: '/themen'
      fullPath: '/admin/stammdaten/themen'
      preLoaderRoute: typeof AdminAuthenticatedStammdatenThemenRouteImport
      parentRoute: typeof AdminAuthenticatedStammdatenRoute
    }
    '/admin/_authenticated/stammdaten/schliesstage': {
      id: '/admin/_authenticated/stammdaten/schliesstage'
      path: '/schliesstage'
      fullPath: '/admin/stammdaten/schliesstage'
      preLoaderRoute: typeof AdminAuthenticatedStammdatenSchliesstageRouteImport
      parentRoute: typeof AdminAuthenticatedStammdatenRoute
    }
    '/admin/_authenticated/stammdaten/raeume': {
      id: '/admin/_authenticated/stammdaten/raeume'
      path: '/raeume'
      fullPath: '/admin/stammdaten/raeume'
      preLoaderRoute: typeof AdminAuthenticatedStammdatenRaeumeRouteImport
      parentRoute: typeof AdminAuthenticatedStammdatenRoute
    }
    '/admin/_authenticated/stammdaten/einrichtungstypen': {
      id: '/admin/_authenticated/stammdaten/einrichtungstypen'
      path: '/einrichtungstypen'
      fullPath: '/admin/stammdaten/einrichtungstypen'
      preLoaderRoute: typeof AdminAuthenticatedStammdatenEinrichtungstypenRouteImport
      parentRoute: typeof AdminAuthenticatedStammdatenRoute
    }
    '/admin/_authenticated/stammdaten/angebotsarten': {
      id: '/admin/_authenticated/stammdaten/angebotsarten'
      path: '/angebotsarten'
      fullPath: '/admin/stammdaten/angebotsarten'
      preLoaderRoute: typeof AdminAuthenticatedStammdatenAngebotsartenRouteImport
      parentRoute: typeof AdminAuthenticatedStammdatenRoute
    }
    '/admin/_authenticated/referenten/$id': {
      id: '/admin/_authenticated/referenten/$id'
      path: '/referenten/$id'
      fullPath: '/admin/referenten/$id'
      preLoaderRoute: typeof AdminAuthenticatedReferentenIdRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/hilfe/marktueberblick': {
      id: '/admin/_authenticated/hilfe/marktueberblick'
      path: '/hilfe/marktueberblick'
      fullPath: '/admin/hilfe/marktueberblick'
      preLoaderRoute: typeof AdminAuthenticatedHilfeMarktueberblickRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/buchungen/neu': {
      id: '/admin/_authenticated/buchungen/neu'
      path: '/buchungen/neu'
      fullPath: '/admin/buchungen/neu'
      preLoaderRoute: typeof AdminAuthenticatedBuchungenNeuRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/buchungen/$id': {
      id: '/admin/_authenticated/buchungen/$id'
      path: '/buchungen/$id'
      fullPath: '/admin/buchungen/$id'
      preLoaderRoute: typeof AdminAuthenticatedBuchungenIdRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedStammdatenRouteChildren {
  AdminAuthenticatedStammdatenAngebotsartenRoute: typeof AdminAuthenticatedStammdatenAngebotsartenRoute
  AdminAuthenticatedStammdatenEinrichtungstypenRoute: typeof AdminAuthenticatedStammdatenEinrichtungstypenRoute
  AdminAuthenticatedStammdatenRaeumeRoute: typeof AdminAuthenticatedStammdatenRaeumeRoute
  AdminAuthenticatedStammdatenSchliesstageRoute: typeof AdminAuthenticatedStammdatenSchliesstageRoute
  AdminAuthenticatedStammdatenThemenRoute: typeof AdminAuthenticatedStammdatenThemenRoute
  AdminAuthenticatedStammdatenIndexRoute: typeof AdminAuthenticatedStammdatenIndexRoute
}

const AdminAuthenticatedStammdatenRouteChildren: AdminAuthenticatedStammdatenRouteChildren =
  {
    AdminAuthenticatedStammdatenAngebotsartenRoute:
      AdminAuthenticatedStammdatenAngebotsartenRoute,
    AdminAuthenticatedStammdatenEinrichtungstypenRoute:
      AdminAuthenticatedStammdatenEinrichtungstypenRoute,
    AdminAuthenticatedStammdatenRaeumeRoute:
      AdminAuthenticatedStammdatenRaeumeRoute,
    AdminAuthenticatedStammdatenSchliesstageRoute:
      AdminAuthenticatedStammdatenSchliesstageRoute,
    AdminAuthenticatedStammdatenThemenRoute:
      AdminAuthenticatedStammdatenThemenRoute,
    AdminAuthenticatedStammdatenIndexRoute:
      AdminAuthenticatedStammdatenIndexRoute,
  }

const AdminAuthenticatedStammdatenRouteWithChildren =
  AdminAuthenticatedStammdatenRoute._addFileChildren(
    AdminAuthenticatedStammdatenRouteChildren,
  )

interface AdminAuthenticatedVerwaltungRouteChildren {
  AdminAuthenticatedVerwaltungEinbettenRoute: typeof AdminAuthenticatedVerwaltungEinbettenRoute
  AdminAuthenticatedVerwaltungEinstellungenRoute: typeof AdminAuthenticatedVerwaltungEinstellungenRoute
  AdminAuthenticatedVerwaltungMitarbeiterRoute: typeof AdminAuthenticatedVerwaltungMitarbeiterRoute
  AdminAuthenticatedVerwaltungIndexRoute: typeof AdminAuthenticatedVerwaltungIndexRoute
}

const AdminAuthenticatedVerwaltungRouteChildren: AdminAuthenticatedVerwaltungRouteChildren =
  {
    AdminAuthenticatedVerwaltungEinbettenRoute:
      AdminAuthenticatedVerwaltungEinbettenRoute,
    AdminAuthenticatedVerwaltungEinstellungenRoute:
      AdminAuthenticatedVerwaltungEinstellungenRoute,
    AdminAuthenticatedVerwaltungMitarbeiterRoute:
      AdminAuthenticatedVerwaltungMitarbeiterRoute,
    AdminAuthenticatedVerwaltungIndexRoute:
      AdminAuthenticatedVerwaltungIndexRoute,
  }

const AdminAuthenticatedVerwaltungRouteWithChildren =
  AdminAuthenticatedVerwaltungRoute._addFileChildren(
    AdminAuthenticatedVerwaltungRouteChildren,
  )

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedAngebotsartenRoute: typeof AdminAuthenticatedAngebotsartenRoute
  AdminAuthenticatedAuswertungenRoute: typeof AdminAuthenticatedAuswertungenRoute
  AdminAuthenticatedEinbettenRoute: typeof AdminAuthenticatedEinbettenRoute
  AdminAuthenticatedEinrichtungstypenRoute: typeof AdminAuthenticatedEinrichtungstypenRoute
  AdminAuthenticatedEinstellungenRoute: typeof AdminAuthenticatedEinstellungenRoute
  AdminAuthenticatedKalenderRoute: typeof AdminAuthenticatedKalenderRoute
  AdminAuthenticatedMarktueberblickRoute: typeof AdminAuthenticatedMarktueberblickRoute
  AdminAuthenticatedMitarbeiterRoute: typeof AdminAuthenticatedMitarbeiterRoute
  AdminAuthenticatedRaeumeRoute: typeof AdminAuthenticatedRaeumeRoute
  AdminAuthenticatedSchliesstageRoute: typeof AdminAuthenticatedSchliesstageRoute
  AdminAuthenticatedStammdatenRoute: typeof AdminAuthenticatedStammdatenRouteWithChildren
  AdminAuthenticatedTestRoute: typeof AdminAuthenticatedTestRoute
  AdminAuthenticatedThemenRoute: typeof AdminAuthenticatedThemenRoute
  AdminAuthenticatedVerwaltungRoute: typeof AdminAuthenticatedVerwaltungRouteWithChildren
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
  AdminAuthenticatedBuchungenIdRoute: typeof AdminAuthenticatedBuchungenIdRoute
  AdminAuthenticatedBuchungenNeuRoute: typeof AdminAuthenticatedBuchungenNeuRoute
  AdminAuthenticatedHilfeMarktueberblickRoute: typeof AdminAuthenticatedHilfeMarktueberblickRoute
  AdminAuthenticatedReferentenIdRoute: typeof AdminAuthenticatedReferentenIdRoute
  AdminAuthenticatedBuchungenIndexRoute: typeof AdminAuthenticatedBuchungenIndexRoute
  AdminAuthenticatedHilfeIndexRoute: typeof AdminAuthenticatedHilfeIndexRoute
  AdminAuthenticatedReferentenIndexRoute: typeof AdminAuthenticatedReferentenIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedAngebotsartenRoute: AdminAuthenticatedAngebotsartenRoute,
  AdminAuthenticatedAuswertungenRoute: AdminAuthenticatedAuswertungenRoute,
  AdminAuthenticatedEinbettenRoute: AdminAuthenticatedEinbettenRoute,
  AdminAuthenticatedEinrichtungstypenRoute:
    AdminAuthenticatedEinrichtungstypenRoute,
  AdminAuthenticatedEinstellungenRoute: AdminAuthenticatedEinstellungenRoute,
  AdminAuthenticatedKalenderRoute: AdminAuthenticatedKalenderRoute,
  AdminAuthenticatedMarktueberblickRoute:
    AdminAuthenticatedMarktueberblickRoute,
  AdminAuthenticatedMitarbeiterRoute: AdminAuthenticatedMitarbeiterRoute,
  AdminAuthenticatedRaeumeRoute: AdminAuthenticatedRaeumeRoute,
  AdminAuthenticatedSchliesstageRoute: AdminAuthenticatedSchliesstageRoute,
  AdminAuthenticatedStammdatenRoute:
    AdminAuthenticatedStammdatenRouteWithChildren,
  AdminAuthenticatedTestRoute: AdminAuthenticatedTestRoute,
  AdminAuthenticatedThemenRoute: AdminAuthenticatedThemenRoute,
  AdminAuthenticatedVerwaltungRoute:
    AdminAuthenticatedVerwaltungRouteWithChildren,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
  AdminAuthenticatedBuchungenIdRoute: AdminAuthenticatedBuchungenIdRoute,
  AdminAuthenticatedBuchungenNeuRoute: AdminAuthenticatedBuchungenNeuRoute,
  AdminAuthenticatedHilfeMarktueberblickRoute:
    AdminAuthenticatedHilfeMarktueberblickRoute,
  AdminAuthenticatedReferentenIdRoute: AdminAuthenticatedReferentenIdRoute,
  AdminAuthenticatedBuchungenIndexRoute: AdminAuthenticatedBuchungenIndexRoute,
  AdminAuthenticatedHilfeIndexRoute: AdminAuthenticatedHilfeIndexRoute,
  AdminAuthenticatedReferentenIndexRoute:
    AdminAuthenticatedReferentenIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminEinladungRoute: AdminEinladungRoute,
  AdminLoginRoute: AdminLoginRoute,
  BuchungDankeRoute: BuchungDankeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
